In [17]:
import sys
# import logging
from pathlib import Path

# ── Path setup ────────────────────────────────────────────────────────────────
ROOT    = Path().resolve().parents[0]
SRC_DIR = ROOT / "src"
for p in [str(ROOT), str(SRC_DIR)]:
    if p not in sys.path:
        sys.path.insert(0, p)
ROOT

WindowsPath('D:/Projects/Madstat/madstrat_backtest')

In [ ]:
# ── Path setup ────────────────────────────────────────────────────────────────
# ROOT    = Path().resolve().parents[1]
# SRC_DIR = ROOT / "src"
# for p in [str(ROOT), str(SRC_DIR)]:
#     if p not in sys.path:
#         sys.path.insert(0, p)

from src.data.process_data import DataProcessor, RAW_DATA_DIR, PROCESSED_DIR

In [69]:
processor = DataProcessor()

In [ ]:
import pandas as pd
raw_data_path = ROOT / "data" / "raw"
# list all CSV files in the raw data directory
daily_file = [f.name for f in raw_data_path.glob("*.csv") if "1d" in f.name]
intraday_file = [f.name for f in raw_data_path.glob("*.csv") if "15m" in f.name]

# file_names
# daily = pd.read_csv(ROOT / "data" / "raw" / daily_file[0])
# df = pd.read_csv(ROOT / "data" / "raw" / intraday_file[0])

In [84]:
daily = processor._load(ROOT / "data" / "raw" / daily_file[0])
df = processor._load(ROOT / "data" / "raw" / intraday_file[0])

2026-05-05 00:27:30,099 | INFO | Loaded 42 rows | 2026-03-04 03:00:00 -> 2026-05-01 02:00:00
2026-05-05 00:27:30,133 | INFO | Loaded 3876 rows | 2026-03-04 00:00:00 -> 2026-05-02 01:45:00

In [53]:
# Lowercase all column names immediately
daily.columns = [c.lower() for c in daily.columns]

# ── Locate and set the datetime index ─────────────────────────────────
# Priority order of candidate column names
dt_candidates = ["datetime", "date", "time", "timestamp"]

dt_col = None
for candidate in dt_candidates:
    if candidate in daily.columns:
        dt_col = candidate
        break

if dt_col:
    # Datetime is a regular column — parse and set as index
    daily[dt_col] = pd.to_datetime(daily[dt_col])
    daily = daily.set_index(dt_col)
    daily.index.name = "datetime"
else:
    # Assume first column is the datetime index (yfinance layout)
    df = pd.read_csv(raw_data_path, index_col=0, parse_dates=True)
    df.columns = [c.lower() for c in df.columns]

In [54]:
daily

                         open      high       low     close     volume
datetime
2026-03-04 03:00:00  5106.335  5206.265  5105.370  5140.945  1224059.0
2026-03-05 03:00:00  5152.485  5195.220  5050.905  5081.380  1240770.0
2026-03-06 03:00:00  5090.810  5176.630  5063.215  5171.500  1161417.0
2026-03-09 02:00:00  5171.950  5171.950  5015.045  5137.910  1394107.0
2026-03-10 02:00:00  5128.805  5238.775  5117.355  5192.510   833109.0
2026-03-11 02:00:00  5191.790  5223.385  5149.155  5176.480   630037.0
2026-03-12 02:00:00  5178.045  5191.790  5055.125  5079.255   804529.0
2026-03-13 02:00:00  5083.865  5128.475  5009.745  5020.600   695124.0
2026-03-16 02:00:00  5014.955  5038.145  4967.775  5006.565   865975.0
2026-03-17 02:00:00  5011.110  5044.900  4973.720  5005.725   665101.0
2026-03-18 02:00:00  5001.960  5016.530  4806.845  4818.415   908731.0
2026-03-19 02:00:00  4824.645  4867.225  4502.365  4650.720  1777919.0
2026-03-20 02:00:00  4659.990  4736.175  4477.540  4497.480  1538222.0
2026-03-23 02:00:00  4472.240  4536.415  4099.125  4406.505  2759675.0
2026-03-24 02:00:00  4382.825  4484.495  4305.880  4474.275  2120905.0
2026-03-25 02:00:00  4476.635  4602.645  4455.885  4506.845  1234234.0
2026-03-26 02:00:00  4521.855  4544.815  4351.355  4378.200  1545708.0
2026-03-27 02:00:00  4388.670  4555.630  4375.525  4493.685  1017271.0
2026-03-30 02:00:00  4512.540  4580.730  4417.430  4510.650  1310697.0
2026-03-31 02:00:00  4517.710  4687.335  4482.660  4667.875  1298919.0
2026-04-01 02:00:00  4674.535  4793.195  4662.125  4758.200  1062604.0
2026-04-02 02:00:00  4758.465  4800.800  4553.850  4676.745  1477021.0
2026-04-06 02:00:00  4638.250  4706.875  4600.850  4649.995   915070.0
2026-04-07 02:00:00  4661.755  4718.960  4607.630  4704.810  1215752.0
2026-04-08 02:00:00  4741.845  4858.215  4699.305  4718.960  1158729.0
2026-04-09 02:00:00  4727.550  4801.390  4698.725  4765.405   949417.0
2026-04-10 02:00:00  4772.620  4794.980  4730.740  4749.685   772355.0
2026-04-13 02:00:00  4670.425  4750.205  4644.465  4740.340   950060.0
2026-04-14 02:00:00  4746.920  4846.370  4745.840  4841.760   745834.0
2026-04-15 02:00:00  4849.155  4871.380  4786.080  4790.940   741540.0
2026-04-16 02:00:00  4798.465  4838.560  4772.575  4790.660   740854.0
2026-04-17 02:00:00  4793.945  4891.540  4767.845  4831.610   893667.0
2026-04-20 02:00:00  4774.815  4827.695  4736.830  4820.115   868597.0
2026-04-21 02:00:00  4825.135  4833.405  4668.620  4720.685  1053867.0
2026-04-22 02:00:00  4726.085  4772.385  4715.780  4740.455   701691.0
2026-04-23 02:00:00  4741.960  4754.200  4664.380  4694.090  1057518.0
2026-04-24 02:00:00  4695.935  4740.570  4658.030  4709.750   876536.0
2026-04-27 02:00:00  4696.875  4729.965  4667.335  4681.955   710688.0
2026-04-28 02:00:00  4682.585  4701.640  4555.135  4596.800  1005632.0
2026-04-29 02:00:00  4598.745  4610.535  4510.095  4543.715  1088560.0
2026-04-30 02:00:00  4540.130  4647.045  4539.685  4622.065   959494.0
2026-05-01 02:00:00  4629.515  4660.585  4560.320  4613.835   798463.0

In [56]:
# Previous week levels built from daily candles
weekly = (
    daily["high"].resample("W-MON", label="left", closed="left").max()
    .to_frame("weekly_high")
    .join(
        daily["low"].resample("W-MON", label="left", closed="left")
        .min()
        .rename("weekly_low")
    )
    .dropna()
)


weekly["PWH"]   = weekly["weekly_high"].shift(1)
weekly["PWL"]   = weekly["weekly_low"].shift(1)

In [57]:
weekly

            weekly_high  weekly_low       PWH       PWL
datetime
2026-03-02     5206.265    5050.905       NaN       NaN
2026-03-09     5238.775    5009.745  5206.265  5050.905
2026-03-16     5044.900    4477.540  5238.775  5009.745
2026-03-23     4602.645    4099.125  5044.900  4477.540
2026-03-30     4800.800    4417.430  4602.645  4099.125
2026-04-06     4858.215    4600.850  4800.800  4417.430
2026-04-13     4891.540    4644.465  4858.215  4600.850
2026-04-20     4833.405    4658.030  4891.540  4644.465
2026-04-27     4729.965    4510.095  4833.405  4658.030

In [58]:
weekly_aligned = weekly[["PWH", "PWL"]].reindex(df.index, method="ffill")

In [60]:
daily['pwh'] = weekly['PWH']
daily

                         open      high       low     close     volume  pwh
datetime
2026-03-04 03:00:00  5106.335  5206.265  5105.370  5140.945  1224059.0  NaN
2026-03-05 03:00:00  5152.485  5195.220  5050.905  5081.380  1240770.0  NaN
2026-03-06 03:00:00  5090.810  5176.630  5063.215  5171.500  1161417.0  NaN
2026-03-09 02:00:00  5171.950  5171.950  5015.045  5137.910  1394107.0  NaN
2026-03-10 02:00:00  5128.805  5238.775  5117.355  5192.510   833109.0  NaN
2026-03-11 02:00:00  5191.790  5223.385  5149.155  5176.480   630037.0  NaN
2026-03-12 02:00:00  5178.045  5191.790  5055.125  5079.255   804529.0  NaN
2026-03-13 02:00:00  5083.865  5128.475  5009.745  5020.600   695124.0  NaN
2026-03-16 02:00:00  5014.955  5038.145  4967.775  5006.565   865975.0  NaN
2026-03-17 02:00:00  5011.110  5044.900  4973.720  5005.725   665101.0  NaN
2026-03-18 02:00:00  5001.960  5016.530  4806.845  4818.415   908731.0  NaN
2026-03-19 02:00:00  4824.645  4867.225  4502.365  4650.720  1777919.0  NaN
2026-03-20 02:00:00  4659.990  4736.175  4477.540  4497.480  1538222.0  NaN
2026-03-23 02:00:00  4472.240  4536.415  4099.125  4406.505  2759675.0  NaN
2026-03-24 02:00:00  4382.825  4484.495  4305.880  4474.275  2120905.0  NaN
2026-03-25 02:00:00  4476.635  4602.645  4455.885  4506.845  1234234.0  NaN
2026-03-26 02:00:00  4521.855  4544.815  4351.355  4378.200  1545708.0  NaN
2026-03-27 02:00:00  4388.670  4555.630  4375.525  4493.685  1017271.0  NaN
2026-03-30 02:00:00  4512.540  4580.730  4417.430  4510.650  1310697.0  NaN
2026-03-31 02:00:00  4517.710  4687.335  4482.660  4667.875  1298919.0  NaN
2026-04-01 02:00:00  4674.535  4793.195  4662.125  4758.200  1062604.0  NaN
2026-04-02 02:00:00  4758.465  4800.800  4553.850  4676.745  1477021.0  NaN
2026-04-06 02:00:00  4638.250  4706.875  4600.850  4649.995   915070.0  NaN
2026-04-07 02:00:00  4661.755  4718.960  4607.630  4704.810  1215752.0  NaN
2026-04-08 02:00:00  4741.845  4858.215  4699.305  4718.960  1158729.0  NaN
2026-04-09 02:00:00  4727.550  4801.390  4698.725  4765.405   949417.0  NaN
2026-04-10 02:00:00  4772.620  4794.980  4730.740  4749.685   772355.0  NaN
2026-04-13 02:00:00  4670.425  4750.205  4644.465  4740.340   950060.0  NaN
2026-04-14 02:00:00  4746.920  4846.370  4745.840  4841.760   745834.0  NaN
2026-04-15 02:00:00  4849.155  4871.380  4786.080  4790.940   741540.0  NaN
2026-04-16 02:00:00  4798.465  4838.560  4772.575  4790.660   740854.0  NaN
2026-04-17 02:00:00  4793.945  4891.540  4767.845  4831.610   893667.0  NaN
2026-04-20 02:00:00  4774.815  4827.695  4736.830  4820.115   868597.0  NaN
2026-04-21 02:00:00  4825.135  4833.405  4668.620  4720.685  1053867.0  NaN
2026-04-22 02:00:00  4726.085  4772.385  4715.780  4740.455   701691.0  NaN
2026-04-23 02:00:00  4741.960  4754.200  4664.380  4694.090  1057518.0  NaN
2026-04-24 02:00:00  4695.935  4740.570  4658.030  4709.750   876536.0  NaN
2026-04-27 02:00:00  4696.875  4729.965  4667.335  4681.955   710688.0  NaN
2026-04-28 02:00:00  4682.585  4701.640  4555.135  4596.800  1005632.0  NaN
2026-04-29 02:00:00  4598.745  4610.535  4510.095  4543.715  1088560.0  NaN
2026-04-30 02:00:00  4540.130  4647.045  4539.685  4622.065   959494.0  NaN
2026-05-01 02:00:00  4629.515  4660.585  4560.320  4613.835   798463.0  NaN

In [49]:
daily

,open,high,low,close,volume,PWH,PWL
datetime,,,,,,,
2026-03-04 03:00:00,5106.335,5206.265,5105.370,5140.945,1224059.0,NaN,NaN
2026-03-05 03:00:00,5152.485,5195.220,5050.905,5081.380,1240770.0,NaN,NaN
2026-03-06 03:00:00,5090.810,5176.630,5063.215,5171.500,1161417.0,NaN,NaN
2026-03-09 02:00:00,5171.950,5171.950,5015.045,5137.910,1394107.0,NaN,NaN
2026-03-10 02:00:00,5128.805,5238.775,5117.355,5192.510,833109.0,NaN,NaN
2026-03-11 02:00:00,5191.790,5223.385,5149.155,5176.480,630037.0,NaN,NaN
2026-03-12 02:00:00,5178.045,5191.790,5055.125,5079.255,804529.0,NaN,NaN
2026-03-13 02:00:00,5083.865,5128.475,5009.745,5020.600,695124.0,NaN,NaN
2026-03-16 02:00:00,5014.955,5038.145,4967.775,5006.565,865975.0,NaN,NaN
2026-03-17 02:00:00,5011.110,5044.900,4973.720,5005.725,665101.0,NaN,NaN
2026-03-18 02:00:00,5001.960,5016.530,4806.845,4818.415,908731.0,NaN,NaN
2026-03-19 02:00:00,4824.645,4867.225,4502.365,4650.720,1777919.0,NaN,NaN
2026-03-20 02:00:00,4659.990,4736.175,4477.540,4497.480,1538222.0,NaN,NaN
2026-03-23 02:00:00,4472.240,4536.415,4099.125,4406.505,2759675.0,NaN,NaN
2026-03-24 02:00:00,4382.825,4484.495,4305.880,4474.275,2120905.0,NaN,NaN
2026-03-25 02:00:00,4476.635,4602.645,4455.885,4506.845,1234234.0,NaN,NaN
2026-03-26 02:00:00,4521.855,4544.815,4351.355,4378.200,1545708.0,NaN,NaN
2026-03-27 02:00:00,4388.670,4555.630,4375.525,4493.685,1017271.0,NaN,NaN
2026-03-30 02:00:00,4512.540,4580.730,4417.430,4510.650,1310697.0,NaN,NaN
2026-03-31 02:00:00,4517.710,4687.335,4482.660,4667.875,1298919.0,NaN,NaN
2026-04-01 02:00:00,4674.535,4793.195,4662.125,4758.200,1062604.0,NaN,NaN
2026-04-02 02:00:00,4758.465,4800.800,4553.850,4676.745,1477021.0,NaN,NaN
2026-04-06 02:00:00,4638.250,4706.875,4600.850,4649.995,915070.0,NaN,NaN
2026-04-07 02:00:00,4661.755,4718.960,4607.630,4704.810,1215752.0,NaN,NaN
2026-04-08 02:00:00,4741.845,4858.215,4699.305,4718.960,1158729.0,NaN,NaN
2026-04-09 02:00:00,4727.550,4801.390,4698.725,4765.405,949417.0,NaN,NaN
2026-04-10 02:00:00,4772.620,4794.980,4730.740,4749.685,772355.0,NaN,NaN
2026-04-13 02:00:00,4670.425,4750.205,4644.465,4740.340,950060.0,NaN,NaN
2026-04-14 02:00:00,4746.920,4846.370,4745.840,4841.760,745834.0,NaN,NaN
2026-04-15 02:00:00,4849.155,4871.380,4786.080,4790.940,741540.0,NaN,NaN
2026-04-16 02:00:00,4798.465,4838.560,4772.575,4790.660,740854.0,NaN,NaN
2026-04-17 02:00:00,4793.945,4891.540,4767.845,4831.610,893667.0,NaN,NaN
2026-04-20 02:00:00,4774.815,4827.695,4736.830,4820.115,868597.0,NaN,NaN
2026-04-21 02:00:00,4825.135,4833.405,4668.620,4720.685,1053867.0,NaN,NaN
2026-04-22 02:00:00,4726.085,4772.385,4715.780,4740.455,701691.0,NaN,NaN
2026-04-23 02:00:00,4741.960,4754.200,4664.380,4694.090,1057518.0,NaN,NaN
2026-04-24 02:00:00,4695.935,4740.570,4658.030,4709.750,876536.0,NaN,NaN
2026-04-27 02:00:00,4696.875,4729.965,4667.335,4681.955,710688.0,NaN,NaN
2026-04-28 02:00:00,4682.585,4701.640,4555.135,4596.800,1005632.0,NaN,NaN
2026-04-29 02:00:00,4598.745,4610.535,4510.095,4543.715,1088560.0,NaN,NaN
2026-04-30 02:00:00,4540.130,4647.045,4539.685,4622.065,959494.0,NaN,NaN
2026-05-01 02:00:00,4629.515,4660.585,4560.320,4613.835,798463.0,NaN,NaN

In [62]:
weekly = pd.DataFrame({
    "open":  df["open"].resample("W").first(),
    "high":  df["high"].resample("W").max(),
    "low":   df["low"].resample("W").min(),
    "close": df["close"].resample("W").last(),
}).dropna()

In [63]:
weekly

                open      high       low     close
datetime
2026-03-01  5173.570  5281.155  5130.235  5278.510
2026-03-08  5368.530  5419.660  4996.275  5171.500
2026-03-15  5171.950  5238.775  5009.745  5020.600
2026-03-22  5014.955  5044.900  4477.540  4497.480
2026-03-29  4472.240  4602.645  4099.125  4493.685
2026-04-05  4512.540  4800.800  4417.430  4676.745
2026-04-12  4638.250  4858.215  4600.850  4749.685
2026-04-19  4670.425  4891.540  4644.465  4831.610
2026-04-26  4774.815  4833.405  4658.030  4709.750

In [86]:
df = processor._add_weekly_levels(df, daily)
df

2026-05-05 00:27:44,470 | INFO | Added: PWH, PWL, PW_EQ
2026-05-05 00:27:44,496 | INFO | Added: WH, WL

,open,high,low,close,volume,PWH,PWL,PW_EQ,WH,WL
datetime,,,,,,,,,,
2026-03-04 00:00:00,5136.130,5149.055,5109.915,5112.470,20183.0,NaN,NaN,NaN,5149.055,5109.915
2026-03-04 00:15:00,5112.380,5121.360,5102.030,5106.825,16329.0,NaN,NaN,NaN,5149.055,5102.030
2026-03-04 00:30:00,5106.830,5119.230,5099.430,5119.120,23260.0,NaN,NaN,NaN,5149.055,5099.430
2026-03-04 00:45:00,5119.135,5128.550,5107.190,5113.395,22060.0,NaN,NaN,NaN,5149.055,5099.430
2026-03-04 01:00:00,5113.385,5127.075,5112.240,5119.125,20531.0,NaN,NaN,NaN,5149.055,5099.430
...,...,...,...,...,...,...,...,...,...,...
2026-05-02 00:45:00,4611.880,4615.450,4609.015,4610.920,14902.0,4833.405,4658.03,4745.7175,4729.965,4510.095
2026-05-02 01:00:00,4610.905,4612.820,4607.220,4611.500,4831.0,4833.405,4658.03,4745.7175,4729.965,4510.095
2026-05-02 01:15:00,4611.555,4616.225,4609.955,4613.430,3419.0,4833.405,4658.03,4745.7175,4729.965,4510.095
2026-05-02 01:30:00,4613.440,4615.145,4610.265,4613.905,4265.0,4833.405,4658.03,4745.7175,4729.965,4510.095
2026-05-02 01:45:00,4613.925,4617.805,4612.700,4613.835,3954.0,4833.405,4658.03,4745.7175,4729.965,4510.095

In [88]:
# Forward-fill the intraday PWH/PWL onto the daily index
# This avoids the resample mismatch when daily index != intraday buckets
daily["PWH"] = df["PWH"].reindex(daily.index, method="ffill")
daily["PWL"] = df["PWL"].reindex(daily.index, method="ffill")
# If exact daily timestamps don't exist in intraday, use nearest prior bar
if daily["PWH"].isna().all():
    daily["PWH"] = df["PWH"].reindex(
        daily.index, method="ffill", tolerance=pd.Timedelta("1D")
    )
    daily["PWL"] = df["PWL"].reindex(
        daily.index, method="ffill", tolerance=pd.Timedelta("1D")
    )
d = daily.dropna(subset=["PWH", "PWL"])

d["FBR_bull"] = (d["high"]  > d["PWH"]) & (d["close"] <= d["PWH"])
d["FBR_bear"] = (d["low"]   < d["PWL"]) & (d["close"] >= d["PWL"])
d["FBR"]      = d["FBR_bull"] | d["FBR_bear"]
d

,open,high,low,close,volume,PWH,PWL,FBR_bull,FBR_bear,FBR
datetime,,,,,,,,,,
2026-03-10 02:00:00,5128.805,5238.775,5117.355,5192.510,833109.0,5206.265,5050.905,True,False,True
2026-03-11 02:00:00,5191.790,5223.385,5149.155,5176.480,630037.0,5206.265,5050.905,True,False,True
2026-03-12 02:00:00,5178.045,5191.790,5055.125,5079.255,804529.0,5206.265,5050.905,False,False,False
2026-03-13 02:00:00,5083.865,5128.475,5009.745,5020.600,695124.0,5206.265,5050.905,False,False,False
2026-03-16 02:00:00,5014.955,5038.145,4967.775,5006.565,865975.0,5206.265,5050.905,False,False,False
2026-03-17 02:00:00,5011.110,5044.900,4973.720,5005.725,665101.0,5238.775,5009.745,False,False,False
2026-03-18 02:00:00,5001.960,5016.530,4806.845,4818.415,908731.0,5238.775,5009.745,False,False,False
2026-03-19 02:00:00,4824.645,4867.225,4502.365,4650.720,1777919.0,5238.775,5009.745,False,False,False
2026-03-20 02:00:00,4659.990,4736.175,4477.540,4497.480,1538222.0,5238.775,5009.745,False,False,False
2026-03-23 02:00:00,4472.240,4536.415,4099.125,4406.505,2759675.0,5238.775,5009.745,False,False,False
2026-03-24 02:00:00,4382.825,4484.495,4305.880,4474.275,2120905.0,5044.900,4477.540,False,False,False
2026-03-25 02:00:00,4476.635,4602.645,4455.885,4506.845,1234234.0,5044.900,4477.540,False,True,True
2026-03-26 02:00:00,4521.855,4544.815,4351.355,4378.200,1545708.0,5044.900,4477.540,False,False,False
2026-03-27 02:00:00,4388.670,4555.630,4375.525,4493.685,1017271.0,5044.900,4477.540,False,True,True
2026-03-30 02:00:00,4512.540,4580.730,4417.430,4510.650,1310697.0,5044.900,4477.540,False,True,True
2026-03-31 02:00:00,4517.710,4687.335,4482.660,4667.875,1298919.0,4602.645,4099.125,False,False,False
2026-04-01 02:00:00,4674.535,4793.195,4662.125,4758.200,1062604.0,4602.645,4099.125,False,False,False
2026-04-02 02:00:00,4758.465,4800.800,4553.850,4676.745,1477021.0,4602.645,4099.125,False,False,False
2026-04-06 02:00:00,4638.250,4706.875,4600.850,4649.995,915070.0,4602.645,4099.125,False,False,False
2026-04-07 02:00:00,4661.755,4718.960,4607.630,4704.810,1215752.0,4800.800,4417.430,False,False,False
2026-04-08 02:00:00,4741.845,4858.215,4699.305,4718.960,1158729.0,4800.800,4417.430,True,False,True
2026-04-09 02:00:00,4727.550,4801.390,4698.725,4765.405,949417.0,4800.800,4417.430,True,False,True
2026-04-10 02:00:00,4772.620,4794.980,4730.740,4749.685,772355.0,4800.800,4417.430,False,False,False
2026-04-13 02:00:00,4670.425,4750.205,4644.465,4740.340,950060.0,4800.800,4417.430,False,False,False
2026-04-14 02:00:00,4746.920,4846.370,4745.840,4841.760,745834.0,4858.215,4600.850,False,False,False
2026-04-15 02:00:00,4849.155,4871.380,4786.080,4790.940,741540.0,4858.215,4600.850,True,False,True
2026-04-16 02:00:00,4798.465,4838.560,4772.575,4790.660,740854.0,4858.215,4600.850,False,False,False
2026-04-17 02:00:00,4793.945,4891.540,4767.845,4831.610,893667.0,4858.215,4600.850,True,False,True
2026-04-20 02:00:00,4774.815,4827.695,4736.830,4820.115,868597.0,4858.215,4600.850,False,False,False
2026-04-21 02:00:00,4825.135,4833.405,4668.620,4720.685,1053867.0,4891.540,4644.465,False,False,False
2026-04-22 02:00:00,4726.085,4772.385,4715.780,4740.455,701691.0,4891.540,4644.465,False,False,False
2026-04-23 02:00:00,4741.960,4754.200,4664.380,4694.090,1057518.0,4891.540,4644.465,False,False,False
2026-04-24 02:00:00,4695.935,4740.570,4658.030,4709.750,876536.0,4891.540,4644.465,False,False,False
2026-04-27 02:00:00,4696.875,4729.965,4667.335,4681.955,710688.0,4891.540,4644.465,False,False,False
2026-04-28 02:00:00,4682.585,4701.640,4555.135,4596.800,1005632.0,4833.405,4658.030,False,False,False
2026-04-29 02:00:00,4598.745,4610.535,4510.095,4543.715,1088560.0,4833.405,4658.030,False,False,False
2026-04-30 02:00:00,4540.130,4647.045,4539.685,4622.065,959494.0,4833.405,4658.030,False,False,False
2026-05-01 02:00:00,4629.515,4660.585,4560.320,4613.835,798463.0,4833.405,4658.030,False,False,False